export const actionConst = {
  CREATE_VIDEO: 1,
  UPDATE_VIDEO: 2,
  DELETE_VIDEO: 3,
  VIEW_VIDEO: 4,
  MANAGE_OPEN_AND_CLOSE_EDIT_DIALOG: 5,
  FETCH_VIDEOS: 6,
  FETCH_CATEGORY: 7,
  SET_NOTIFICATIONS: 8,
  SET_SERVER_NOTIFICATION: 9,
};
